---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ops-udesk-cn-v1beta1-scalenotifyconfig
  failurePolicy: Fail
  name: mscalenotifyconfig-v1beta1.kb.io
  rules:
  - apiGroups:
    - ops.udesk.cn
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - scalenotifyconfigs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ops-udesk-cn-v1beta1-scalenotifyconfig
  failurePolicy: Fail
  name: vscalenotifyconfig-v1beta1.kb.io
  rules:
  - apiGroups:
    - ops.udesk.cn
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - scalenotifyconfigs
  sideEffects: None
