---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ops.udesk.cn
  resources:
  - scalenotifyconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ops.udesk.cn
  resources:
  - scalenotifyconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - ops.udesk.cn
  resources:
  - scalenotifyconfigs/status
  verbs:
  - get
  - patch
  - update
