---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules: 
  - apiGroups: ["udesk.cn/ops"]
    resources: ["alertscales"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]


