---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ops.udesk.cn
  resources:
  - alertscales
  - podrebalances
  - scalenotifyconfigs
  - scalenotifymsgtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ops.udesk.cn
  resources:
  - alertscales/finalizers
  - podrebalances/finalizers
  - scalenotifyconfigs/finalizers
  - scalenotifymsgtemplates/finalizers
  verbs:
  - update
- apiGroups:
  - ops.udesk.cn
  resources:
  - alertscales/status
  - podrebalances/status
  - scalenotifyconfigs/status
  - scalenotifymsgtemplates/status
  verbs:
  - get
  - patch
  - update
