apiVersion: ops.udesk.cn/v1beta1
kind: ScaleNotifyConfig
metadata:
  labels:
    app.kubernetes.io/name: udesk-ops-operator
    app.kubernetes.io/managed-by: kustomize
  name: scalenotifyconfig-wxwork-default
  namespace: default
spec:
  default: true
  type: WXWorkRobot
  config:
    webhookURL: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=9911e070-e548-4fb8-aad6-f3a43fe1da15"
    atUsers: ["user1", "user2"]
    atAll: true
