apiVersion: ops.udesk.cn/v1beta1
kind: AlertScale
metadata:
  name: example-alertscale-10
  namespace: default
spec:
  scaleDuration: 10m
  scaleNotificationType: email
  scaleReason: High CPU Usage
  scaleTarget:
    apiVersion: apps/v1
    kind: Deployment
    name: example-deployment
    namespace: default
  scaleThreshold: 30
  scaleTimeout: 5m
