//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertScale) DeepCopyInto(out *AlertScale) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertScale.
func (in *AlertScale) DeepCopy() *AlertScale {
	if in == nil {
		return nil
	}
	out := new(AlertScale)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlertScale) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertScaleList) DeepCopyInto(out *AlertScaleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AlertScale, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertScaleList.
func (in *AlertScaleList) DeepCopy() *AlertScaleList {
	if in == nil {
		return nil
	}
	out := new(AlertScaleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlertScaleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertScaleSpec) DeepCopyInto(out *AlertScaleSpec) {
	*out = *in
	out.ScaleTarget = in.ScaleTarget
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertScaleSpec.
func (in *AlertScaleSpec) DeepCopy() *AlertScaleSpec {
	if in == nil {
		return nil
	}
	out := new(AlertScaleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertScaleStatus) DeepCopyInto(out *AlertScaleStatus) {
	*out = *in
	in.ScaleStatus.DeepCopyInto(&out.ScaleStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertScaleStatus.
func (in *AlertScaleStatus) DeepCopy() *AlertScaleStatus {
	if in == nil {
		return nil
	}
	out := new(AlertScaleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodRebalance) DeepCopyInto(out *PodRebalance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodRebalance.
func (in *PodRebalance) DeepCopy() *PodRebalance {
	if in == nil {
		return nil
	}
	out := new(PodRebalance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodRebalance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodRebalanceList) DeepCopyInto(out *PodRebalanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodRebalance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodRebalanceList.
func (in *PodRebalanceList) DeepCopy() *PodRebalanceList {
	if in == nil {
		return nil
	}
	out := new(PodRebalanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodRebalanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodRebalanceSpec) DeepCopyInto(out *PodRebalanceSpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	in.Strategy.DeepCopyInto(&out.Strategy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodRebalanceSpec.
func (in *PodRebalanceSpec) DeepCopy() *PodRebalanceSpec {
	if in == nil {
		return nil
	}
	out := new(PodRebalanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodRebalanceStatus) DeepCopyInto(out *PodRebalanceStatus) {
	*out = *in
	in.RebalanceBeginTime.DeepCopyInto(&out.RebalanceBeginTime)
	in.RebalanceEndTime.DeepCopyInto(&out.RebalanceEndTime)
	if in.RebalancedPods != nil {
		in, out := &in.RebalancedPods, &out.RebalancedPods
		*out = make([]RebalancedPodInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodRebalanceStatus.
func (in *PodRebalanceStatus) DeepCopy() *PodRebalanceStatus {
	if in == nil {
		return nil
	}
	out := new(PodRebalanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodRebalanceStrategy) DeepCopyInto(out *PodRebalanceStrategy) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Threshold != nil {
		in, out := &in.Threshold, &out.Threshold
		*out = new(RebalanceThreshold)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodRebalanceStrategy.
func (in *PodRebalanceStrategy) DeepCopy() *PodRebalanceStrategy {
	if in == nil {
		return nil
	}
	out := new(PodRebalanceStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RebalanceThreshold) DeepCopyInto(out *RebalanceThreshold) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(int32)
		**out = **in
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(int32)
		**out = **in
	}
	if in.PodCountImbalance != nil {
		in, out := &in.PodCountImbalance, &out.PodCountImbalance
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RebalanceThreshold.
func (in *RebalanceThreshold) DeepCopy() *RebalanceThreshold {
	if in == nil {
		return nil
	}
	out := new(RebalanceThreshold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RebalancedPodInfo) DeepCopyInto(out *RebalancedPodInfo) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RebalancedPodInfo.
func (in *RebalancedPodInfo) DeepCopy() *RebalancedPodInfo {
	if in == nil {
		return nil
	}
	out := new(RebalancedPodInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleNotifyConfig) DeepCopyInto(out *ScaleNotifyConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleNotifyConfig.
func (in *ScaleNotifyConfig) DeepCopy() *ScaleNotifyConfig {
	if in == nil {
		return nil
	}
	out := new(ScaleNotifyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScaleNotifyConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleNotifyConfigList) DeepCopyInto(out *ScaleNotifyConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScaleNotifyConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleNotifyConfigList.
func (in *ScaleNotifyConfigList) DeepCopy() *ScaleNotifyConfigList {
	if in == nil {
		return nil
	}
	out := new(ScaleNotifyConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScaleNotifyConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleNotifyConfigSpec) DeepCopyInto(out *ScaleNotifyConfigSpec) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleNotifyConfigSpec.
func (in *ScaleNotifyConfigSpec) DeepCopy() *ScaleNotifyConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ScaleNotifyConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleNotifyConfigStatus) DeepCopyInto(out *ScaleNotifyConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleNotifyConfigStatus.
func (in *ScaleNotifyConfigStatus) DeepCopy() *ScaleNotifyConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ScaleNotifyConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleNotifyMsgTemplate) DeepCopyInto(out *ScaleNotifyMsgTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleNotifyMsgTemplate.
func (in *ScaleNotifyMsgTemplate) DeepCopy() *ScaleNotifyMsgTemplate {
	if in == nil {
		return nil
	}
	out := new(ScaleNotifyMsgTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScaleNotifyMsgTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleNotifyMsgTemplateList) DeepCopyInto(out *ScaleNotifyMsgTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScaleNotifyMsgTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleNotifyMsgTemplateList.
func (in *ScaleNotifyMsgTemplateList) DeepCopy() *ScaleNotifyMsgTemplateList {
	if in == nil {
		return nil
	}
	out := new(ScaleNotifyMsgTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScaleNotifyMsgTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleNotifyMsgTemplateSpec) DeepCopyInto(out *ScaleNotifyMsgTemplateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleNotifyMsgTemplateSpec.
func (in *ScaleNotifyMsgTemplateSpec) DeepCopy() *ScaleNotifyMsgTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ScaleNotifyMsgTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleNotifyMsgTemplateStatus) DeepCopyInto(out *ScaleNotifyMsgTemplateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleNotifyMsgTemplateStatus.
func (in *ScaleNotifyMsgTemplateStatus) DeepCopy() *ScaleNotifyMsgTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(ScaleNotifyMsgTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleStatus) DeepCopyInto(out *ScaleStatus) {
	*out = *in
	in.ScaleBeginTime.DeepCopyInto(&out.ScaleBeginTime)
	in.ScaleEndTime.DeepCopyInto(&out.ScaleEndTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleStatus.
func (in *ScaleStatus) DeepCopy() *ScaleStatus {
	if in == nil {
		return nil
	}
	out := new(ScaleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleTarget) DeepCopyInto(out *ScaleTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleTarget.
func (in *ScaleTarget) DeepCopy() *ScaleTarget {
	if in == nil {
		return nil
	}
	out := new(ScaleTarget)
	in.DeepCopyInto(out)
	return out
}
